<?php
$this->css(
    [
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));

$local = Pi::service('i18n')->getLocale();
if ($local = 'fa') {
    $this->css(
        [
            $this->assetModule('css/persianDatepicker.css'),
        ]
    );
    $this->js(
        [
            $this->assetModule('js/moment.min.js'),
            $this->assetModule('js/moment-jalali.js'),
            $this->assetModule('js/persianDatepicker.min.js'),
        ]
    );
}
?>
<?php $currentFlashMessages = $this->flashMessenger()->renderCurrent(); ?>
<?php if (trim($currentFlashMessages)) { ?>
    <div class="alert alert-dismissable alert-info">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <div><?php echo $currentFlashMessages; ?></div>
    </div>
    <?php $this->flashMessenger()->clearMessages() ?>
<?php } ?>
<div id="event-form" class="clearfix">
    <h3><?php echo $this->escape($title); ?></h3>
    <?php echo $this->form($form); ?>
</div>
<?php if ($local == 'fa') { ?>
    <script>
        // https://github.com/jalaali/moment-jalaali
        // https://momentjs.com/docs/#/parsing/string-format/
        $(document).ready(function () {

            $('.event-time-start-view').persianDatepicker({
                <?php if (isset($event['time_start']) && !empty($event['time_start'])) { ?>
                selectedBefore: !0,
                selectedDate: moment(<?php echo $event['time_start']; ?>, 'X').format('jYYYY/jM/jD'),
                <?php } ?>
                onSelect: function () {
                    // debugger
                    var old = $('.event-time-start-view').val();
                    // UNIX timestamp
                    var timestampDate = moment(old, 'jYYYY/jM/jD').format('X');
                    // Set val
                    $('.event-time-start').val(timestampDate);
                }
            });

            $('.event-time-end-view').persianDatepicker({
                <?php if (isset($event['time_end']) && !empty($event['time_end'])) { ?>
                selectedBefore: !0,
                selectedDate: moment(<?php echo $event['time_end']; ?>, 'X').format('jYYYY/jM/jD'),
                <?php } ?>
                onSelect: function () {
                    // debugger
                    var old = $('.event-time-end-view').val();
                    // UNIX timestamp
                    var timestampDate = moment(old, 'jYYYY/jM/jD').format('X');
                    // Set val
                    $('.event-time-end').val(timestampDate);
                }
            });

        });
    </script>
<?php } else { ?>
    <script>
        $(document).ready(function () {
            $(".event-time-start").datepicker().on('changeDate', function (selected) {
                var minDate = new Date(selected.date.valueOf());
                $('.event-time-end').datepicker('setStartDate', minDate);
            });
            var minDate = new Date($(".event-time-start").val());
            $('.event-time-end').datepicker('setStartDate', minDate);
        });
    </script>
<?php } ?>

<script>
    $(document).ready(function () {
        var registerCanOnChange = function () {
            if ($('[type=checkbox][name=register_can]').prop('checked')) {
                $('[data-name=register_stock] label i.text-danger').show();
                $('[name=register_stock]').attr('required', true);
            } else {
                $('[data-name=register_stock] label i.text-danger').hide();
                $('[name=register_stock]').removeAttr('required');
            }
        };

        $('[name=register_can]').change(
            registerCanOnChange
        );

        registerCanOnChange();

        if ($(".event-time-start").length) {
            $(".event-time-start").datepicker().on('changeDate', function (selected) {
                var minDate = new Date(selected.date.valueOf());
                $('.event-time-end').datepicker('setStartDate', minDate);
            });
            var minDate = new Date($(".event-time-start").val());
            $('.event-time-end').datepicker('setStartDate', minDate);
        }

    });
</script>