<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="event-form" class="clearfix">
    <h3><?php echo $this->escape($title); ?></h3>
    <?php echo $this->form($form); ?>
    <?php include $this->template('front/partial/crop'); ?>
    <script>
        jQuery(document).ready(function(){
            parseCrop();
        });
    </script>
</div>
<script type="text/javascript">
    (function ($) {
        
        $(".event-time-start").datepicker().on('changeDate', function (selected) {
            var minDate = new Date(selected.date.valueOf());
            $('.event-time-end').datepicker('setStartDate', minDate);
        });
        
        $("#event-form").on("click", "button", function () {
            systemMessage.wait("<?php _e('Remove image event in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.status == 1) {
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>