<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="card bg-light">
        <div class="card-body">
            <?php echo $this->form($form, 'inline'); ?>
        </div>
    </div>
    <?php if (!empty($list)) { ?>
        <h3><?php _e('List of events'); ?></h3>
        <table class="table table-striped table-bordered table-hover table-responsive-md table-sm mt-3">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $event) { ?>
                <?php
                if ($event['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($event['status'] == 2) {
                    $labelIdClass = 'label-warning';
                } elseif ($event['status'] == 3) {
                    $labelIdClass = 'label-warning';
                } elseif ($event['status'] == 4) {
                    $labelIdClass = 'label-warning';
                } elseif ($event['status'] == 5) {
                    $labelIdClass = 'label-danger';
                }
                ?>
                <tr>
                    <td>
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($event['id']); ?></span>
                    </td>
                    <td>
                        <div class="clearfix">
                            <?php echo $this->escape($event['title']); ?>
                        </div>
                        <div class="clearfix">
                            <?php if (!empty($event['time_start']) && !empty($event['time_end'])) {
                                 echo sprintf('%s %s %s %s', __('From'), $event['time_start_view'], __('to'), $event['time_start_view']);
                             } elseif (!empty($event['time_start'])) {
                                 echo $this->escape($event['time_start_view']);
                             } ?>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-success btn-sm" title="<?php _e('View'); ?>" href="<?php echo $event['eventUrl']; ?>" target="_blank">
                            <i class="fa fa-eye"></i> <?php _e('View'); ?>
                        </a>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', ['action' => 'update', 'id' => $event['id']]); ?>">
                            <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
        <ul class="list-inline">
            <li class="list-inline-item badge badge-success"><?php _e('Published'); ?></li>
            <li class="list-inline-item badge badge-warning"><?php _e('Pending review'); ?></li>
            <li class="list-inline-item badge badge-warning"><?php _e('Draft'); ?></li>
            <li class="list-inline-item badge badge-warning"><?php _e('Private'); ?></li>
            <li class="list-inline-item badge badge-danger"><?php _e('Trash'); ?></li>
        </ul>
    <?php } ?>
</div>