<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>

<?php $currentFlashMessages = $this->flashMessenger()->renderCurrent(); ?>
<?php if(trim($currentFlashMessages)) : ?>
    <div class="alert alert-dismissable alert-info">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <div><?php echo $currentFlashMessages; ?></div>
    </div>
    <?php $this->flashMessenger()->clearMessages() ?>
<?php endif; ?>

<div id="event-form" class="clearfix">
    <h3><?php echo $this->escape($title); ?></h3>
    <?php echo $this->form($form); ?>
</div>
<script type="text/javascript">
    (function ($) {

        $(".event-time-start").datepicker().on('changeDate', function (selected) {
            var minDate = new Date(selected.date.valueOf());
            $('.event-time-end').datepicker('setStartDate', minDate);
        });
    })(jQuery)
</script>