<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingForm">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseForm" aria-expanded="false" aria-controls="collapseForm">
                        <i class="fa fa-plus"></i> <?php _e('Filter events'); ?>
                    </a>
                </h4>
            </div>
            <div id="collapseForm" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingForm">
                <div class="panel-body">
                    <?php echo $this->form($form); ?>
                </div>
            </div>
        </div>
    </div>
    <?php if (!empty($list)) { ?>
        <h3><?php _e('List of events'); ?></h3>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $event) { ?>
                <?php
                if ($event['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($event['status'] == 2) {
                    $labelIdClass = 'label-warning';
                } elseif ($event['status'] == 3) {
                    $labelIdClass = 'label-warning';
                } elseif ($event['status'] == 4) {
                    $labelIdClass = 'label-warning';
                } elseif ($event['status'] == 5) {
                    $labelIdClass = 'label-danger';
                }
                ?>
                <tr>
                    <td>
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($event['id']); ?></span>
                    </td>
                    <td>
                        <div class="clearfix">
                            <?php echo $this->escape($event['title']); ?>
                        </div>
                        <div class="clearfix">
                            <?php if (!empty($event['time_start']) && !empty($event['time_end'])) { ?>
                                <?php echo _b('From') ?> <?php echo $this->escape($event['time_start_view']); ?>
                                <?php echo _b('to') ?> <?php echo $this->escape($event['time_end_view']); ?>
                            <?php } elseif (!empty($event['time_start'])) { ?>
                                <?php echo $this->escape($event['time_start_view']); ?>
                            <?php } ?>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-success" title="<?php _e('View'); ?>" href="<?php echo $event['eventUrl']; ?>"
                           target="_blank"><i class="fa fa-eye"></i> <?php _e('View'); ?></a>
                        <a class="btn btn-primary" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', array('action' => 'update', 'id' => $event['id'])); ?>"><i
                                class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
        <p>
            <span class="label label-success"><?php _e('Published'); ?></span>
            <span class="label label-warning"><?php _e('Pending review'); ?></span>
            <span class="label label-warning"><?php _e('Draft'); ?></span>
            <span class="label label-warning"><?php _e('Private'); ?></span>
            <span class="label label-danger"><?php _e('Trash'); ?></span>
        </p>
    <?php } ?>
</div>