<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of all orders'); ?></h3>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Name'); ?></th>
            <th><?php _e('Event'); ?></th>
        </tr>
        <?php foreach ($list as $order) { ?>
            <?php
            if ($order['status'] == 1) {
                $labelIdClass = 'label-success';
            } else {
                $labelIdClass = 'label-warning';
            }
            ?>
            <tr>
                <td>
                    <span class="label <?php echo $labelIdClass; ?>">
                        <?php echo $this->escape($order['id']); ?>
                    </span>
                </td>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-link btn-sm" data-toggle="modal" data-target="#orderUser<?php echo $this->escape($order['id']); ?>">
                        <?php echo $this->escape($order['user']['name']); ?>
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="orderUser<?php echo $this->escape($order['id']); ?>" tabindex="-1" role="dialog" aria-labelledby="orderUserLabel<?php echo $this->escape($order['id']); ?>">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    <h4 class="modal-title" id="orderUserLabel<?php echo $this->escape($order['id']); ?>">Modal title</h4>
                                </div>
                                <div class="modal-body">
                                    <pre><?php print_r($order['user']); ?></pre>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-link btn-sm" data-toggle="modal" data-target="#orderPlan<?php echo $this->escape($order['id']); ?>">
                        <?php echo $this->escape($order['eventInfo']['title']); ?>
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="orderPlan<?php echo $this->escape($order['id']); ?>" tabindex="-1" role="dialog" aria-labelledby="orderPlanLabel<?php echo $this->escape($order['id']); ?>">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    <h4 class="modal-title" id="orderPlanLabel<?php echo $this->escape($order['id']); ?>">Modal title</h4>
                                </div>
                                <div class="modal-body">
                                    <pre><?php print_r($order); ?></pre>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>



