<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of all orders'); ?></h3>
    <table class="table table-striped table-bordered table-hover table-responsive-md table-sm mt-3">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Name'); ?></th>
            <th><?php _e('Number'); ?></th>
            <th><?php _e('Total'); ?></th>
            <th><?php _e('Event'); ?></th>
            <th><?php _e('Status'); ?></th>
        </tr>
        <?php foreach ($list as $order) { ?>
            <?php
            if ($order['status'] == 1) {
                $labelIdClass = 'label-success';
            } else {
                $labelIdClass = 'label-warning';
            }
            ?>
            <tr>
                <td>
                    <span class="label <?php echo $labelIdClass; ?>">
                        <?php echo $this->escape($order['id']); ?>
                    </span>
                </td>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-link btn-sm" data-toggle="modal" data-target="#orderUser<?php echo $this->escape($order['id']); ?>">
                        <?php echo !empty($order['user']['name']) ? $this->escape($order['user']['name']) : ''; ?>
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="orderUser<?php echo $this->escape($order['id']); ?>" tabindex="-1" role="dialog"
                         aria-labelledby="orderUserLabel<?php echo $this->escape($order['id']); ?>">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    <h4 class="modal-title" id="orderUserLabel<?php echo $this->escape($order['id']); ?>">Modal title</h4>
                                </div>
                                <div class="modal-body">
                                    <pre><?php print_r($order['user']); ?></pre>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td><?php echo $this->escape($order['number_view']); ?></td>
                <td><?php echo $this->escape($order['price_view']); ?></td>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-link btn-sm" data-toggle="modal" data-target="#orderPlan<?php echo $this->escape($order['id']); ?>">
                        <?php echo $this->escape($order['eventInfo']['title']); ?>
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="orderPlan<?php echo $this->escape($order['id']); ?>" tabindex="-1" role="dialog"
                         aria-labelledby="orderPlanLabel<?php echo $this->escape($order['id']); ?>">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    <h4 class="modal-title" id="orderPlanLabel<?php echo $this->escape($order['id']); ?>"><?php echo $this->escape($order['eventInfo']['title']); ?></h4>
                                </div>
                                <div class="modal-body">
                                    <div class="card">
                                        <img src="<?php echo Pi::api('doc', 'media')->getSingleLinkUrl($order['main_image'])->setConfigModule('news')->thumb('medium'); ?>" class="card-img-top" alt="...">
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <?php _e('Total price') ?> : <strong><?php echo $this->escape($order['price_view']); ?></strong>
                                            </li>
                                            <li class="list-group-item">
                                                <?php _e('Number') ?> : <strong><?php echo $this->escape($order['number_view']); ?> <?php _e('person') ?></strong>
                                            </li>
                                        </ul>
                                        <div class="card-body">
                                            <button href="#" class="btn btn-primary"><?php _e('Accept order'); ?></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td><?php echo $this->escape($order['status_view']); ?></td>
            </tr>
        <?php } ?>
    </table>
</div>



