<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Import events from guide module'); ?>"
           href="<?php echo $this->url('', array('controller' => 'tools', 'action' => 'import')); ?>"><i
                class="fa fa-cogs"></i> <?php _e('Import events from guide module'); ?></a>
        <a class="btn btn-primary" title="<?php _e('Sitemap'); ?>"
           href="<?php echo $this->url('', array('action' => 'sitemap')); ?>"><i
                class="fa fa-sitemap"></i> <?php _e('Sitemap'); ?></a>
        <a class="btn btn-primary" title="<?php _e('Image'); ?>"
           href="<?php echo $this->url('', array('action' => 'image')); ?>"><i
                class="fa fa-picture-o"></i> <?php _e('Image'); ?></a>
    </p>

    <h3><?php echo $this->escape($title); ?></h3>

    <div class="alert alert-success"><?php echo $this->escape($message); ?></div>
    <?php echo $this->form($form); ?>
</div>