<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Import events from guide module'); ?>"
           href="<?php echo $this->url('', array('controller' => 'tools', 'action' => 'import')); ?>"><i
                class="fa fa-cogs"></i> <?php _e('Import events from guide module'); ?></a>

        <a class="btn btn-primary" title="<?php _e('Sitemap'); ?>"
           href="<?php echo $this->url('', array('action' => 'sitemap')); ?>"><i
                class="fa fa-sitemap"></i> <?php _e('Sitemap'); ?></a>

        <a class="btn btn-primary" title="<?php _e('Fill Time End if empty'); ?>"
           href="<?php echo $this->url('', array('action' => 'fillTimeEnd')); ?>"><i
                    class="fa fa-cogs"></i> <?php _e('Fill Time End if empty'); ?></a>
    </p>
</div>