<div class="container guide-width-description-wrapper">
    <div class="category-width-description">
        <h1 class="p-name"><?php echo $this->escape($title); ?></h1>
        <?php if (!empty($config['text_description_index'])) { ?>
            <div class="clearfix"><?php echo $config['text_description_index']; ?></div>
        <?php } ?>
    </div>
</div>
<div class="category-width-image">
    <img class="img-responsive" src="<?php echo $config['image_homepage']; ?>"
         alt="<?php echo $this->escape($title); ?>">
</div>