<?php Pi::service('i18n')->load(array('module/event', 'default')); ?>
<h5><?php _e('Favourite event'); ?></h5>

<table id="item-list" class="table table-striped table-bordered table-condensed">
    <tr>
        <th class="col-md-<?php echo $isProfil ? '2' : '1' ?>"><?php _e('Image'); ?></th>
        <th class="col-md-<?php echo $isProfil ? '4' : '3' ?>"><?php _e('Name'); ?></th>
        <th class="col-md-<?php echo $isProfil ? '3' : '2' ?>"><?php _e('Category'); ?></th>
        <?php if (!$isProfil) { ?>
            <th class="col-md-3"><?php _e('Period'); ?></th>
        <?php } ?>
        <th class="col-md-3"><?php _e('Locations'); ?></th>
         

    </tr>
    <?php foreach ($favouriteList as $favourite) { ?>
        <tr>
            <td class="favorite-nopadding text-center">
                 <img style="width:100%" src="<?php echo $this->escape($favourite['image']); ?>"
                     alt="<?php echo $this->escape($favourite['title']); ?>"/>
            </td>
            <td>
                <a title="<?php echo $this->escape($favourite['title']); ?>"
                   href="<?php echo $this->escape($favourite['url']); ?>"><?php echo $this->escape($favourite['title']); ?></a>
                <?php if ($isProfil) { ?>
                    (<?php echo $this->escape(($favourite['period'])); ?>)
                <?php } ?>
            </td>
            <td><?php foreach ($favourite['categories'] as $category) { ?>
                    <span class="guide-margin"><a title="<?php echo $this->escape($category['title']); ?>"
                                                  href="<?php echo $this->escape($category['categoryUrl']); ?>"><?php echo $this->escape($category['title']); ?></a></span>
                <?php } ?>
            </td>
            <?php if (!$isProfil) { ?>
                <td><?php echo $this->escape(($favourite['period'])); ?></td>
            <?php } ?>
            <td><span class="guide-margin"><?php echo $this->escape($favourite['location']); ?></span>
        </tr>
    <?php } ?>
</table>
