<?php

// Add StickyJs
$this->js($this->assetModule('js/jquery.hc-sticky.js'));

$script = <<<'EOT'
$(document).ready(function(){
    $(".event-single-sidebar").hcSticky({
        responsive : true,
        top: $('#pi-header nav').height() + 20,
        stickTo: $('.stickyContainer'),
        offResolutions: -992
    });
    
    $('.event-single-sidebar div.modal').insertAfter('.wrapper-sticky');
    
  });
EOT;

$this->headScript()->appendScript($script);