<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="page-header clearfix">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <?php if (!empty($config['text_description_index']) && isset($page) && $page == 1) { ?>
        <div class="well event-description">
            <?php echo $config['text_description_index']; ?>
        </div>
    <?php } ?>
    <?php if (!empty($eventList)) { ?>
        <div class="event-list clearfix">
            <?php foreach ($eventList as $event) { ?>
                <div class="event-single clearfix h-event" itemscope itemtype="http://schema.org/Event">
                    <div class="row">
                        <div class="col-md-3">
                            <?php if ($event['image']) { ?>
                                <a itemprop="url" title="<?php echo $this->escape($event['title']); ?>"
                                   href="<?php echo $this->escape($event['eventUrl']); ?>">
                                    <img itemprop="image" class="img-responsive img-rounded u-photo"
                                         src="<?php echo $this->escape($event['thumbUrl']); ?>"
                                         alt="<?php echo $this->escape($event['title']); ?>"/>
                                </a>
                            <?php } ?>
                        </div>
                        <div class="col-md-9">
                            <div class="event-single-title p-name" itemprop="name">
                                <h2 class="clearfix">
                                    <a itemprop="url" title="<?php echo $this->escape($event['title']); ?>"
                                       href="<?php echo $this->escape($event['eventUrl']); ?>">
                                        <?php echo $this->escape($event['title']); ?>
                                    </a>
                                    <?php if ($event['subtitle']) { ?>
                                        <small class="pull-right"><?php echo $this->escape($event['subtitle']); ?></small>
                                    <?php } ?>
                                </h2>
                            </div>
                            <div class="event-single-information small">
                                <ul class="clearfix list-inline event-time">
                                    <?php if (!empty($event['time_start']) && !empty($event['time_end'])) { ?>
                                        <li><i class="fa fa-clock-o"></i> <?php _e('From') ?></li>
                                        <li class="dt-start"><?php echo $this->escape($event['time_start_view']); ?></li>
                                        <li><?php _e('to') ?></li>
                                        <li class="dt-end"><?php echo $this->escape($event['time_end_view']); ?></li>
                                        <meta itemprop="startDate" content="<?php echo $this->escape(date("Y-m-d H:i:s", $event['time_start'])); ?>" />
                                        <meta itemprop="endDate" content="<?php echo $this->escape(date("Y-m-d H:i:s", $event['time_end'])); ?>" />
                                    <?php } elseif (!empty($event['time_start'])) { ?>
                                        <li class="event-single-time dt-start"><i class="fa fa-clock-o"></i> <?php echo $this->escape($event['time_start_view']); ?></li>
                                        <meta itemprop="startDate" content="<?php echo $this->escape(date("Y-m-d H:i:s", $event['time_start'])); ?>" />
                                    <?php } ?>
                                    <?php if (!empty($event['topics'])) { ?>
                                        <li><i class="fa fa-folder"></i></li>
                                        <?php foreach ($event['topics'] as $eventTopic) { ?>
                                            <li class="p-category" itemprop="about">
                                                <a title="<?php echo $this->escape($eventTopic['title']); ?>"
                                                   href="<?php echo $this->escape($eventTopic['url']); ?>"><?php echo $this->escape($eventTopic['title']); ?></a>
                                            </li>
                                        <?php } ?>
                                    <?php } ?>
                                    <?php if (!empty($event['register_price'])) { ?>
                                        <li class="p-price" itemprop="price" content="<?php echo $this->escape($event['register_price']); ?>">
                                            <i class="fa fa-money"></i><?php echo $this->escape($event['register_price_view']); ?>
                                        </li>
                                        <meta itemprop="priceCurrency" content="<?php echo $this->escape($event['price_currency']); ?>" />
                                    <?php } ?>
                                    <li><i class="fa fa-eye"></i> <?php echo $this->escape(_number($event['hits'])); ?></li>
                                </ul>
                            </div>
                            <?php if (!empty($event['text_summary'])) { ?>
                                <div class="event-single-summery clearfix p-summary" itemprop="description">
                                    <?php echo $event['text_summary']; ?>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } ?>
</div>