<?php
// Load angular custom js
$script = <<<'EOT'
var app = angular.module('event', ['angularUtils.directives.dirPagination']);
app.controller('listdata',function($scope, $http){
    $scope.events = [];
    $('.ajax-spinner').show();
    $http.get("%s").success(function(response){
        $scope.events = response;
        $('.ajax-spinner').hide();
    });
    $scope.sortKey = "%s";
    $scope.reverse = true;
    $scope.sort = function(keyname){
        $scope.sortKey = keyname;
        $scope.reverse = !$scope.reverse;
    }
});
EOT;
$script = sprintf(
    $script,
    $filterUrl,
    'time_publish'
);

// Load header files
$this->jQuery();
$this->angular();
$this->js($this->assetModule('js/dirPagination.js'));
$this->css($this->assetModule('css/front.css'));
$this->footScript()->appendScript($script);

// Set Open Graph tags for meta
$this->doctype('HTML5');
if (isset($category['title']) && !empty($category['title'])) {
    $this->headMeta($this->escape($category['title']), 'og:title', 'property');
} elseif (isset($title) && !empty($title)) {
    $this->headMeta($this->escape($title), 'og:title', 'property');
}
if (isset($category['topicUrl']) && !empty($category['topicUrl'])) {
    $this->headMeta($this->escape($category['topicUrl']), 'og:url', 'property');
} else{
    $this->headMeta(Pi::url($this->url('', array('module' => 'event'))), 'og:url', 'property');
}
if (isset($category['text_summary']) && !empty($category['text_summary'])) {
    $this->headMeta(_strip($category['text_summary']), 'og:description', 'property');
} elseif(isset($config['text_description_index']) && !empty($config['text_description_index'])) {
    $this->headMeta(_strip($config['text_description_index']), 'og:description', 'property');
}
if (isset($category['largeUrl']) && !empty($category['largeUrl'])) {
    $this->headMeta($this->escape($category['largeUrl']), 'og:image', 'property');
} elseif(isset($config['image_homepage']) && !empty($config['image_homepage'])) {
    $this->headMeta($this->escape($config['image_homepage']), 'og:image', 'property');
}

// Set twitter for meta
if (isset($category['title']) && !empty($category['title'])) {
    $this->headMeta($this->escape($category['title']), 'twitter:title');
} elseif (isset($title) && !empty($title)) {
    $this->headMeta($this->escape($title), 'twitter:title');
}
if (isset($category['text_summary']) && !empty($category['text_summary'])) {
    $this->headMeta(_strip($category['text_summary']), 'twitter:description');
} elseif(isset($config['text_description_index']) && !empty($config['text_description_index'])) {
    $this->headMeta(_strip($config['text_description_index']), 'twitter:description');
}
if (isset($category['largeUrl']) && !empty($category['largeUrl'])) {
    $this->headMeta($this->escape($category['largeUrl']), 'twitter:image');
} elseif(isset($config['image_homepage']) && !empty($config['image_homepage'])) {
    $this->headMeta($this->escape($config['image_homepage']), 'twitter:image');
}
?>
<div class="clearfix row">
    <div class="ajax-spinner">
        <img src="<?php echo $this->assetModule('image/spinner.gif'); ?>" class="ajax-spinner-loader"/>
    </div>
    <div class="col-sm-12 col-md-12">
        <?php if (isset($isHomepage) && $isHomepage == 1) { ?>
            <?php if (!empty($config['image_homepage'])) { ?>
                <div class="category-width-description">
                    <h1 class="p-name" itemprop="name"><?php echo $this->escape($title); ?></h1>
                    <?php if (!empty($config['text_description_index'])) { ?>
                        <div class="clearfix"><?php echo $config['text_description_index']; ?></div>
                    <?php } ?>
                </div>
                <div class="category-width-image">
                    <img class="img-responsive" src="<?php echo $config['image_homepage']; ?>"
                         alt="<?php echo $this->escape($title); ?>">
                </div>
            <?php } else { ?>
                <div class="page-header">
                    <h1 class="p-name" itemprop="name"><?php echo $this->escape($title); ?></h1>
                </div>
                <?php if (!empty($config['text_description_index'])) { ?>
                    <div class="clearfix well"><?php echo $config['text_description_index']; ?></div>
                <?php } ?>
            <?php } ?>
        <?php } elseif (isset($isCategoryPage) && $isCategoryPage == 1) { ?>
            <?php if (!empty($category['largeUrl'])) { ?>
                <div class="category-width-description">
                    <h1 class="p-name" itemprop="name"><?php echo $this->escape($category['title']); ?></h1>
                    <?php if (!empty($category['text_summary'])) { ?>
                        <div class="clearfix"><?php echo $category['text_summary']; ?></div>
                    <?php } ?>
                </div>
                <div class="category-width-image">
                    <img class="img-responsive" src="<?php echo $category['largeUrl']; ?>"
                         alt="<?php echo $this->escape($category['title']); ?>">
                </div>
            <?php } else { ?>
                <div class="page-header">
                    <h1 class="p-name" itemprop="name"><?php echo $this->escape($category['title']); ?></h1>
                </div>
            <?php } ?>
            <?php if (!empty($category['text_description'])) { ?>
                <div class="clearfix well"><?php echo $category['text_description']; ?></div>
            <?php } ?>
        <?php } ?>
    </div>
    <div class="col-sm-12 col-md-3">
        <div class="event-search-form clearfix">
            <div class="page-header">
                <h4><?php _e('Search on this group'); ?></h4>
            </div>
            <form>
                <div class="form-group">
                    <label><?php _e('Title'); ?></label>
                    <input type="text" ng-model="filterTitle" class="form-control">
                </div>
                <div class="form-group">
                    <label><?php _e('Event time'); ?></label>
                    <select ng-model="filterTime" class="form-control">
                        <option value=""><?php _e('All'); ?></option>
                        <option value="thisWeek"><?php _e('This week'); ?></option>
                        <option value="nextWeek"><?php _e('Next week'); ?></option>
                        <option value="thisMonth"><?php _e('This month'); ?></option>
                        <option value="nextMonth"><?php _e('Next month'); ?></option>
                        <option value="nextTwoMonth"><?php _e('Next two months'); ?></option>
                        <option value="nextThreeMonth"><?php _e('Next three months'); ?></option>
                        <option value="nextAllMonth"><?php _e('Next months'); ?></option>
                        <option value="expired"><?php _e('Expired'); ?></option>
                    </select>
                </div>
                <?php if (isset($categoryList) && !empty($categoryList) && $isCategoryPage == 0) { ?>
                    <div class="form-group">
                        <label><?php _e('Category'); ?></label>
                        <select ng-model="filterCategory" class="form-control">
                            <option value=""><?php _e('All'); ?></option>
                            <?php foreach ($categoryList as $category) { ?>
                                <option
                                    value="<?php echo $category['value']; ?>"><?php echo $category['title']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                <?php } ?>
                <?php if (isset($locationList) && !empty($locationList)) { ?>
                    <div class="form-group">
                        <label><?php _e('Location'); ?></label>
                        <select ng-model="filterLocation" class="form-control">
                            <option value=""><?php _e('All'); ?></option>
                            <?php foreach ($locationList as $location) { ?>
                                <option
                                    value="<?php echo $location['value']; ?>"><?php echo $location['title']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                <?php } ?>
                <?php if (isset($priceFilterList) && !empty($priceFilterList)) { ?>
                    <div class="form-group">
                        <label><?php _e('Price'); ?></label>
                        <select ng-model="filterPrice" class="form-control">
                            <option value=""><?php _e('All'); ?></option>
                            <?php foreach ($priceFilterList as $priceFilter) { ?>
                                <option
                                    value="<?php echo $priceFilter['value']; ?>"><?php echo $priceFilter['title']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                <?php } ?>
            </form>
        </div>
    </div>
    <div class="col-sm-12 col-md-9" ng-controller="listdata">
        <div class="clearfix">
            <div class="event-list clearfix">
                <div class="clearfix event-sort">
                    <ul class="list-inline">
                        <li><?php _e('Sort by'); ?> :</li>
                        <li class="event-sort-type" ng-click="sort('time_publish')"><?php _e('Time'); ?> <i
                                class="fa sort-icon" ng-show="sortKey=='time_publish'"
                                ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="event-sort-type" ng-click="sort('hits')"><?php _e('Hits'); ?> <i class="fa sort-icon"
                                                                                                    ng-show="sortKey=='hits'"
                                                                                                    ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i>
                        </li>
                        <li class="event-sort-type" ng-click="sort('title')"><?php _e('Title'); ?> <i
                                class="fa sort-icon" ng-show="sortKey=='title'"
                                ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="event-sort-type" ng-click="sortKey=''"><?php _e('Default'); ?></li>
                    </ul>
                </div>
                <div class="clearfix">
                    <?php if ($config['view_list_type'] == 'list') { ?>
                        <div dir-paginate="event in events|orderBy:sortKey:reverse|filter: {title : filterTitle, location : filterLocation , category : filterCategory, time_level : filterTime, price_filter : filterPrice} |itemsPerPage:<?php echo $config['view_perpage']; ?>"
                             class="event-single clearfix h-event" itemscope itemtype="http://schema.org/Event">
                            <div class="row">
                                <div class="col-md-3 event-single-image" ng-if="event.image">
                                    <div class="text-center">
                                        <a itemprop="url" title="{{event.title}}"
                                           href="{{event.eventUrl}}">
                                            <img itemprop="image" class="img-responsive img-rounded u-photo center-block"
                                                 src="{{event.thumbUrl}}"
                                                 alt="{{event.title}}"/>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-md-9 event-single-body">
                                    <div class="p-name clearfix" itemprop="name">
                                        <h2 class="event-single-title">
                                            <a itemprop="url" title="{{event.title}}"
                                               href="{{event.eventUrl}}">
                                                {{event.title}}
                                            </a>
                                        </h2>
                                    </div>
                                    <div class="event-single-information small">
                                        <ul class="clearfix list-inline event-time">
                                            <li ng-if="event.time_view">
                                                <i class="fa fa-clock-o"></i> {{event.time_view}}
                                                <meta ng-if="event.time_start_view" itemprop="startDate"
                                                      content="{{event.time_start_view}}"/>
                                                <meta ng-if="event.time_end_view" itemprop="endDate"
                                                      content="{{event.time_end_view}}"/>
                                            </li>
                                            <li ng-if="event.register_price" class="p-price" itemprop="price"
                                                content="{{event.register_price}}">
                                                <i class="fa fa-money"></i> {{event.register_price_view}}
                                            </li>
                                            <meta ng-if="event.register_price" itemprop="priceCurrency"
                                                  content="{{event.price_currency}}"/>
                                            <li><i class="fa fa-eye"></i> {{event.hits}}</li>
                                        </ul>
                                    </div>
                                    <div class="event-single-summery clearfix p-summary" itemprop="description"
                                         ng-if="event.text_summary">
                                        {{event.text_summary}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } elseif ($config['view_list_type'] == 'box') { ?>
                        <div dir-paginate="event in events|orderBy:sortKey:reverse|filter: {title : filterTitle, location : filterLocation , category : filterCategory, time_level : filterTime, price_filter : filterPrice} |itemsPerPage:<?php echo $config['view_perpage']; ?>"
                             class="col-md-3 event-single clearfix h-event" itemscope itemtype="http://schema.org/Event">
                            <div class="thumbnail">
                                <div class="event-single-image" ng-if="event.image">
                                    <div class="text-center">
                                        <a itemprop="url" title="{{event.title}}"
                                           href="{{event.eventUrl}}">
                                            <img itemprop="image" class="img-responsive img-rounded u-photo center-block"
                                                 src="{{event.thumbUrl}}"
                                                 alt="{{event.title}}"/>
                                        </a>
                                    </div>
                                </div>
                                <div class="caption">
                                    <div class="p-name clearfix" itemprop="name">
                                        <h2 class="event-single-title">
                                            <a itemprop="url" title="{{event.title}}"
                                               href="{{event.eventUrl}}">
                                                {{event.title}}
                                            </a>
                                        </h2>
                                    </div>
                                    <div class="event-single-information small">
                                        <ul class="clearfix list-inline event-time">
                                            <li ng-if="event.time_view">
                                                <i class="fa fa-clock-o"></i> {{event.time_view}}
                                                <meta ng-if="event.time_start_view" itemprop="startDate"
                                                      content="{{event.time_start_view}}"/>
                                                <meta ng-if="event.time_end_view" itemprop="endDate"
                                                      content="{{event.time_end_view}}"/>
                                            </li>
                                            <li ng-if="event.register_price" class="p-price" itemprop="price"
                                                content="{{event.register_price}}">
                                                <i class="fa fa-money"></i> {{event.register_price_view}}
                                            </li>
                                            <meta ng-if="event.register_price" itemprop="priceCurrency"
                                                  content="{{event.price_currency}}"/>
                                            <li><i class="fa fa-eye"></i> {{event.hits}}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <div class="paginator">
                <dir-pagination-controls
                    max-size="<?php echo $config['view_perpage']; ?>"
                    direction-links="true"
                    boundary-links="true">
                </dir-pagination-controls>
            </div>
        </div>
    </div>
</div>