<?php
// Set title and summary
if (!empty($event['time_start']) && !empty($event['time_end'])) {
    $time = sprintf(
        '%s %s %s %s',
        __('From'),
        $this->escape($event['time_start_view']),
        __('to'),
        $this->escape($event['time_end_view'])
    );
} elseif (!empty($event['time_start'])) {
    $time = $this->escape($event['time_start_view']);
}
$title = sprintf('%s - %s', $event['title'], $time);
$summary = sprintf('%s - %s', !empty($event['text_summary']) ? $event['text_summary'] : $event['title'], $time);
// Set script
$script = <<<'EOT'
    $('.gallery').each(function() {
    	$(this).magnificPopup({
       		delegate: 'a',
       		type: 'image',
       		gallery: {
      			enabled:true
       		}
    	});
	});
EOT;
// Load files
$this->css($this->assetModule('css/front.css'));
$this->jQuery(array(
    'extension/jquery.magnific-popup.min.js',
    'extension/magnific-popup.css',
));
$this->footScript()->appendScript($script);
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($title, 'og:title', 'property');
$this->headMeta($event['eventUrl'], 'og:url', 'property');
if (isset($event['text_summary']) && !empty($event['text_summary'])) {
    $this->headMeta($event['text_summary'], 'og:description', 'property');
}
if (!empty($event['largeUrl'])) {
    $this->headMeta($this->escape($event['largeUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta($title, 'og:title', 'property');
$this->headMeta($summary, 'twitter:description');
if (isset($event['largeUrl']) && !empty($event['largeUrl'])) {
    $this->headMeta('summary_large_image', 'twitter:card');
    $this->headMeta($this->escape($event['largeUrl']), 'twitter:image');
}
?>
<div class="clearfix h-event singleEvent" itemscope itemtype="http://schema.org/Event">
    <div class="clearfix itemHead page-header">
        <div class="itemTitle p-name" itemprop="name">
            <h1 class="clearfix">
                <?php echo $this->escape($event['title']); ?>
                <?php if ($event['subtitle']) { ?>
                    <small class="pull-right"><?php echo $this->escape($event['subtitle']); ?></small>
                <?php } ?>
            </h1>
        </div>
    </div>
    <div class="clearfix itemUnderHead">
        <ul class="text-muted list-inline text-right pull-right">
            <li><i class="fa fa-calendar"></i> <?php _e('Date'); ?>
                : <?php echo $this->escape($event['time_update_view']); ?></li>
            <li><i class="fa fa-eye"></i> <?php _e('Viewed'); ?>
                : <?php echo _number($this->escape($event['hits'])); ?> <?php _e('Times'); ?></li>
            <?php if (!empty($event['topics'])) { ?>
                <li><i class="fa fa-folder"></i> <?php _e('Category'); ?> : </li>
                <?php foreach ($event['topics'] as $eventTopic) { ?>
                    <li class="p-category" itemprop="about">
                        <a title="<?php echo $eventTopic['title']; ?>"
                           href="<?php echo $eventTopic['url']; ?>"><?php echo $eventTopic['title']; ?></a>
                    </li>
                <?php } ?>
            <?php } ?>
        </ul>
    </div>
    <div class="clearfix">
        <div class="col-md-8">
            <?php if (!empty($event['text_summary'])) { ?>
                <div class="clearfix p-summary" itemprop="description">
                    <?php echo $event['text_summary']; ?>
                </div>
            <?php } ?>
            <div class="clearfix eventTime">
                <h2><?php _e('Key Event Elements'); ?></h2>
                <ul class="list-unstyled">
                    <?php if (!empty($event['time_start']) && !empty($event['time_end'])) { ?>
                        <li><?php _e('From') ?></li>
                        <li class="dt-start" itemprop="startDate"><?php echo $this->escape($event['time_start_view']); ?></li>
                        <li><?php _e('to') ?></li>
                        <li class="dt-end" itemprop="endDate"><?php echo $this->escape($event['time_end_view']); ?></li>
                    <?php } elseif (!empty($event['time_start'])) { ?>
                        <li class="event-single-time dt-start" itemprop="startDate"><?php echo $this->escape($event['time_start_view']); ?></li>
                    <?php } ?>
                    <?php if (!empty($event['organizer_name'])) { ?>
                        <li itemscope itemtype="http://schema.org/Organization">
                            <i class="fa fa-user"></i> <?php _e('Organizer name') ?> <span itemprop="name"><?php echo $this->escape($event['organizer_name']); ?></span>
                        </li>
                    <?php } ?>
                    <?php if (!empty($event['source_url'])) { ?>
                        <li class="u-url" itemprop="url">
                            <i class="fa fa-external-link"></i> <a title="<?php _e('Organizer Website') ?>"
                                                                   href="<?php echo $this->escape($event['source_url']); ?>" target="_blank"><?php _e('Organizer Website') ?></a>
                        </li>
                    <?php } ?>
                    <?php if (!empty($event['address'])) { ?>
                        <li itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                            <?php _e('Address') ?> : <span itemprop="addressLocality"><?php echo $this->escape($event['address']); ?></span>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <?php if (!empty($event['offer_url']) || !empty($event['register_price'])) { ?>
                <div class="clearfix" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                    <h2><?php echo sprintf(__('Participate/Register to %s'), $this->escape($event['title'])); ?></h2>
                    <?php if (!empty($event['offer_url'])) { ?>
                        <div itemprop="url"><i class="fa fa-external-link"></i> <a title="<?php _e('Register to the event') ?>"  href="<?php echo $this->escape($event['offer_url']); ?>" target="_blank"><?php _e('Register to the event') ?></a></div>
                    <?php } ?>
                    <?php if (!empty($event['register_price'])) { ?>
                        <div class="p-price" itemprop="price" content="<?php echo $this->escape($event['register_price']); ?>">
                            <?php _e('Minimum Price') ?> : <?php echo $this->escape($event['register_price_view']); ?>
                             </div>
                        <meta itemprop="priceCurrency" content="<?php echo $this->escape($event['price_currency']); ?>" />
                    <?php } ?>
                    <?php if (!empty($event['register_details'])) { ?>
                        <br />
                        <div class="clearfix" itemprop="description">
                            <?php echo $event['register_details']; ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
            <?php if (!empty($event['text_description'])) { ?>
                <div class="clearfix p-summary" itemprop="description">
                    <h2><?php _e('Description'); ?></h2>
                    <?php echo $event['text_description']; ?>
                </div>
            <?php } ?>
        </div>
        <div class="col-md-4">
            <div class="event-image-main clearfix u-photo gallery">
                <a href="<?php echo $this->escape($event['largeUrl']); ?>"
                   title="<?php echo $this->escape($event['title']); ?>" itemprop="image">
                    <img class="img-responsive img-thumbnail" src="<?php echo $this->escape($event['mediumUrl']); ?>"
                         alt="<?php echo $this->escape($event['title']); ?>" itemprop="image"/>
                </a>
            </div>
            <br />
            <?php if (!empty($event['guideItemInfo'])) { ?>
                <div class="guide-item-related clearfix">
                    <div class="page-header">
                        <h2><?php _e('Related items'); ?></h2>
                    </div>
                    <div class="thumbnails">
                        <?php foreach ($event['guideItemInfo'] as $guideItemInfo) { ?>
                            <div class="guide-item-box h-review">
                                <div class="thumbnail p-item h-card">
                                    <?php if ($guideItemInfo['image']) { ?>
                                        <a class="u-url" title="<?php echo $this->escape($guideItemInfo['title']); ?>"
                                           href="<?php echo $this->escape($guideItemInfo['itemUrl']); ?>">
                                            <img class="img-responsive u-photo"
                                                 src="<?php echo $this->escape($guideItemInfo['itemimageUrl']); ?>"
                                                 alt="<?php echo $this->escape($guideItemInfo['title']); ?>"/>
                                        </a>
                                    <?php } ?>
                                    <h3 class="p-name">
                                        <a class="u-url" title="<?php echo $this->escape($guideItemInfo['title']); ?>"
                                           href="<?php echo $this->escape($guideItemInfo['itemUrl']); ?>">
                                            <?php echo $this->escape($guideItemInfo['title']); ?>
                                        </a>
                                    </h3>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
            <?php if (!empty($event['guideLocationInfo'])) { ?>
                <div class="guide-item-related clearfix">
                    <div class="page-header">
                        <h2><?php _e('Related locations'); ?></h2>
                    </div>
                    <div class="thumbnails">
                        <?php foreach ($event['guideLocationInfo'] as $guideLocationInfo) { ?>
                            <div class="guide-item-box h-review">
                                <div class="thumbnail p-item h-card">
                                    <?php if ($guideLocationInfo['image']) { ?>
                                        <a class="u-url" title="<?php echo $this->escape($guideLocationInfo['title']); ?>"
                                           href="<?php echo $this->escape($guideLocationInfo['locationUrl']); ?>">
                                            <img class="img-responsive u-photo"
                                                 src="<?php echo $this->escape($guideLocationInfo['itemimageUrl']); ?>"
                                                 alt="<?php echo $this->escape($guideLocationInfo['title']); ?>"/>
                                        </a>
                                    <?php } ?>
                                    <h3 class="p-name">
                                        <a class="u-url" title="<?php echo $this->escape($guideLocationInfo['title']); ?>"
                                           href="<?php echo $this->escape($guideLocationInfo['locationUrl']); ?>">
                                            <?php echo $this->escape($guideLocationInfo['title']); ?>
                                        </a>
                                    </h3>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
            <?php if (!empty($event['guideCategoryInfo'])) { ?>
                <div class="guide-item-related clearfix">
                    <div class="page-header">
                        <h2><?php _e('Related categories'); ?></h2>
                    </div>
                    <div class="thumbnails">
                        <?php foreach ($event['guideCategoryInfo'] as $guideCategoryInfo) { ?>
                            <div class="guide-item-box h-review">
                                <div class="thumbnail p-item h-card">
                                    <?php if ($guideCategoryInfo['image']) { ?>
                                        <a class="u-url" title="<?php echo $this->escape($guideCategoryInfo['title']); ?>"
                                           href="<?php echo $this->escape($guideCategoryInfo['categoryUrl']); ?>">
                                            <img class="img-responsive u-photo"
                                                 src="<?php echo $this->escape($guideCategoryInfo['itemimageUrl']); ?>"
                                                 alt="<?php echo $this->escape($guideCategoryInfo['title']); ?>"/>
                                        </a>
                                    <?php } ?>
                                    <h3 class="p-name">
                                        <a class="u-url" title="<?php echo $this->escape($guideCategoryInfo['title']); ?>"
                                           href="<?php echo $this->escape($guideCategoryInfo['categoryUrl']); ?>">
                                            <?php echo $this->escape($guideCategoryInfo['title']); ?>
                                        </a>
                                    </h3>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
            <?php if ($config['social_sharing']) { ?>
                <div class="clearfix">
                    <div class="col-md-12 col-sm-12 col-xs-12 socialSharingText">
                        <strong><?php _e('Share if you like'); ?></strong>
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-12 socialSharing">
                        <?php echo $this->socialSharing(
                            $config['social_sharing'],
                            $title,
                            $event['eventUrl'],
                            $event['largeUrl']
                        ); ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>