<?php
$this->css(array(
    $this->assetModule('css/front.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->backbone();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>

<?php $currentFlashMessages = $this->flashMessenger()->renderCurrent(); ?>
<?php if(trim($currentFlashMessages)) : ?>
    <div class="alert alert-dismissable alert-info">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <div><?php echo $currentFlashMessages; ?></div>
    </div>
    <?php $this->flashMessenger()->clearMessages() ?>
<?php endif; ?>

<div id="event-form" class="clearfix">
    <div class="guide-manage clearfix">
        <div class="col-md-3">
            <?php $sideActive = 'event'; ?>
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <h1><?php echo $this->escape($title); ?></h1>
            </div>
            <div id="event-form">
                <?php echo $this->form($form); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    (function ($) {
        $(".event-time-start").datepicker().on('changeDate', function (selected) {
            var minDate = new Date(selected.date.valueOf());
            $('.event-time-end').datepicker('setStartDate', minDate);
        });

        $('.form-group[data-name="guide_item"]').insertBefore('.form-group[data-name="title"]');
    })(jQuery)
</script>