<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="col-md-3">
        <?php $sideActive = 'event'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?php _e('List of orders on this event'); ?></h1>
        </div>

    </div>
</div>