<?php
$this->css(array(
    $this->assetModule('css/front.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->backbone();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="event-form" class="clearfix">
    <div class="guide-manage clearfix">
        <div class="col-md-3">
            <?php $sideActive = 'event'; ?>
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
        <div class="col-md-9">
            <div id="event-form">
                <h3><?php echo $this->escape($title); ?></h3>
                <?php echo $this->form($form); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    (function ($) {
        $("#event-form").on("click", "button", function () {
            systemMessage.wait("<?php _e('Remove image event in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.status == 1) {
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>