<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="event-manage clearfix row">
        <div class="col-md-3">
            <?php $sideActive = 'event'; ?>
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
        <div class="col-md-9">

            <div class="pull-right">
                <a class="btn btn-primary" href="<?php echo $this->url('', array('action' => 'update')); ?>" title="<?php _e('New event'); ?>">
                    <i class="fa fa-plus"></i> <?php _e('New event'); ?>
                </a>
            </div>
            <div class="page-header">
                <h1><?php echo $this->escape($title); ?></h1>
            </div>
            <?php if (!empty($events)) { ?>
                <table id="item-list" class="table table-striped table-bordered table-condensed">
                    <tr>
                        <th><?php _e('ID'); ?></th>
                        <th><?php _e('Title'); ?></th>
                        <th><?php _e('Start'); ?></th>
                        <th><?php _e('End'); ?></th>
                        <th><?php _e('Action'); ?></th>
                    </tr>
                    <?php foreach ($events as $event) { ?>
                        <?php
                        if ($event['status'] == 1) {
                            $labelIdClass = 'label-success';
                        } else {
                            $labelIdClass = 'label-warning';
                        }
                        ?>
                        <tr>
                            <td><span
                                    class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($event['id']); ?></span>
                            </td>
                            <td><?php echo $this->escape($event['title']); ?></td>
                            <td><?php echo $this->escape((empty($event['time_start'])) ? '' : _date($event['time_start'], array('pattern' => 'yyyy-MM-dd'))); ?></td>
                            <td><?php echo $this->escape((empty($event['time_end'])) ? '' : _date($event['time_end'], array('pattern' => 'yyyy-MM-dd'))); ?></td>
                            <td>
                                <div class="text-nowrap">
                                    <?php if ($event['status'] == 1) { ?>
                                        <a class="btn btn-success btn-xs" title="<?php _e('View'); ?>"
                                           href="<?php echo $this->escape( Pi::url(Pi::service('url')->assemble('event', array('module' => 'event','controller' => 'index','slug' => $event['slug'])))); ?>" target="_blank"><i
                                                class="fa fa-eye"></i> <?php _e('View'); ?></a>
                                    <?php } ?>
                                    <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                                       href="<?php echo $this->url('', array('action' => 'update', 'id' => $event['id'])); ?>"><i
                                            class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                                    <?php if ($config['order_active']) { ?>
                                    <a class="btn btn-primary btn-xs" title="<?php _e('List of orders'); ?>"
                                       href="<?php echo $this->url('', array('action' => 'order', 'id' => $event['id'])); ?>"><i
                                            class="fa fa-shopping-cart"></i> <?php _e('List of orders'); ?></a>
                                    <?php } ?>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                </table>
                <p>
                    <span class="label label-success"><?php _e('Published'); ?></span>
                    <span class="label label-warning"><?php _e('Pending review'); ?></span>
                </p>
            <?php } ?>
        </div>
    </div>
</div>