<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="event-manage clearfix">
    <div class="col-md-3">
        <?php $sideActive = 'event'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?php echo $this->escape($title); ?></h1>
            <?php 
                if ($event['register_stock'] > 0) {                                                               
                    echo sprintf(__('%s registred / %s places (%s left)'), $event['register_sales'], $event['register_stock'], $event['register_stock'] - $event['register_sales']);
                } else {
                    echo sprintf(__('%s registred'), $event['register_sales']);
                }
            ?>
        </div>

        <?php if (!empty($list)) { ?>
            <table class="table table-striped table-bordered table-condensed">
                <tr>
                    <th><?php _e('ID'); ?></th>
                    <th><?php _e('Name'); ?></th>
                    <th><?php _e('Number'); ?></th>
                    <th><?php _e('Total'); ?></th>
                    <th><?php _e('Code'); ?></th>
                </tr>
                <?php foreach ($list as $order) { ?>
                    <tr>
                        <td><?php echo $this->escape($order['id']); ?></td>
                        <td><?php echo $this->escape($order['user']['name']); ?></td>
                        <td><?php echo $this->escape($order['number_view']); ?></td>
                        <td><?php echo $this->escape($order['total_view']); ?></td>
                        <td><?php echo $this->escape($order['code_public']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        <?php } else { ?>
            <div class="alert alert-danger" role="alert">
                <?php _e('This event still have no online register !'); ?>
            </div>
        <?php } ?>
    </div>
</div>