<?php /* $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="col-md-3">
        <?php $sideActive = 'event'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?php _e('List of your registered events'); ?></h1>
        </div>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Event'); ?></th>
                <th><?php _e('Start time'); ?></th>
                <th><?php _e('Number'); ?></th>
                <th><?php _e('Total'); ?></th>
            </tr>
            <?php foreach ($list as $order) { ?>
            <tr>
                <td><?php echo $this->escape($order['id']); ?></td>
                <td>
                    <a href="<?php echo $this->escape($order['orderUrl']); ?>">
                        <?php echo $this->escape($order['eventInfo']['title']); ?>
                    </a>
                </td>
                <td><?php echo $this->escape($order['time_start_view']); ?></td>
                <td><?php echo $this->escape($order['number_view']); ?></td>
                <td><?php echo $this->escape($order['total_view']); ?></td>
            </tr>
            <?php } ?>
        </table>
    </div>
</div>
<?php */ ?>